package ru.course.web.entity;
// Generated Jul 23, 2018 3:32:39 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Course generated by hbm2java
 */
public class Course  implements java.io.Serializable {


     private Integer courseId;
     private Professor professor;
     private String name;
     private int number;
     private Float cost;
     private Set passingCourses = new HashSet(0);

    public Course() {
    }

	
    public Course(String name, int number) {
        this.name = name;
        this.number = number;
    }
    public Course(Professor professor, String name, int number, Float cost, Set passingCourses) {
       this.professor = professor;
       this.name = name;
       this.number = number;
       this.cost = cost;
       this.passingCourses = passingCourses;
    }
   
    public Integer getCourseId() {
        return this.courseId;
    }
    
    public void setCourseId(Integer courseId) {
        this.courseId = courseId;
    }
    public Professor getProfessor() {
        return this.professor;
    }
    
    public void setProfessor(Professor professor) {
        this.professor = professor;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public int getNumber() {
        return this.number;
    }
    
    public void setNumber(int number) {
        this.number = number;
    }
    public Float getCost() {
        return this.cost;
    }
    
    public void setCost(Float cost) {
        this.cost = cost;
    }
    public Set getPassingCourses() {
        return this.passingCourses;
    }
    
    public void setPassingCourses(Set passingCourses) {
        this.passingCourses = passingCourses;
    }




}


