package ru.course.web.entity;
// Generated Jul 23, 2018 3:32:39 PM by Hibernate Tools 4.3.1



/**
 * PassingCourse generated by hbm2java
 */
public class PassingCourse  implements java.io.Serializable {


     private Integer couPassId;
     private Course course;
     private Student student;
     private Float avgMark;
     private Integer marksCount;
     private Integer examMark;

    public PassingCourse() {
    }

	
    public PassingCourse(Course course, Student student) {
        this.course = course;
        this.student = student;
    }
    public PassingCourse(Course course, Student student, Float avgMark, Integer marksCount, Integer examMark) {
       this.course = course;
       this.student = student;
       this.avgMark = avgMark;
       this.marksCount = marksCount;
       this.examMark = examMark;
    }
   
    public Integer getCouPassId() {
        return this.couPassId;
    }
    
    public void setCouPassId(Integer couPassId) {
        this.couPassId = couPassId;
    }
    public Course getCourse() {
        return this.course;
    }
    
    public void setCourse(Course course) {
        this.course = course;
    }
    public Student getStudent() {
        return this.student;
    }
    
    public void setStudent(Student student) {
        this.student = student;
    }
    public Float getAvgMark() {
        return this.avgMark;
    }
    
    public void setAvgMark(Float avgMark) {
        this.avgMark = avgMark;
    }
    public Integer getMarksCount() {
        return this.marksCount;
    }
    
    public void setMarksCount(Integer marksCount) {
        this.marksCount = marksCount;
    }
    public Integer getExamMark() {
        return this.examMark;
    }
    
    public void setExamMark(Integer examMark) {
        this.examMark = examMark;
    }




}


