package ru.course.web.entity;
// Generated Jul 23, 2018 3:32:39 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Professor generated by hbm2java
 */
public class Professor  implements java.io.Serializable {


     private Integer profId;
     private String name;
     private String address;
     private String telephone;
     private Float payment;
     private Set courses = new HashSet(0);

    public Professor() {
    }

	
    public Professor(String name, String address) {
        this.name = name;
        this.address = address;
    }
    public Professor(String name, String address, String telephone, Float payment, Set courses) {
       this.name = name;
       this.address = address;
       this.telephone = telephone;
       this.payment = payment;
       this.courses = courses;
    }
   
    public Integer getProfId() {
        return this.profId;
    }
    
    public void setProfId(Integer profId) {
        this.profId = profId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getTelephone() {
        return this.telephone;
    }
    
    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }
    public Float getPayment() {
        return this.payment;
    }
    
    public void setPayment(Float payment) {
        this.payment = payment;
    }
    public Set getCourses() {
        return this.courses;
    }
    
    public void setCourses(Set courses) {
        this.courses = courses;
    }




}


