package ru.course.web.entity;
// Generated Jul 23, 2018 3:32:39 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Student generated by hbm2java
 */
public class Student  implements java.io.Serializable {


     private Integer studentId;
     private String name;
     private String address;
     private String telephone;
     private String email;
     private int zachNom;
     private Float avgAcadPerformance;
     private Set passingCourses = new HashSet(0);

    public Student() {
    }

	
    public Student(String name, String address, int zachNom) {
        this.name = name;
        this.address = address;
        this.zachNom = zachNom;
    }
    public Student(String name, String address, String telephone, String email, int zachNom, Float avgAcadPerformance, Set passingCourses) {
       this.name = name;
       this.address = address;
       this.telephone = telephone;
       this.email = email;
       this.zachNom = zachNom;
       this.avgAcadPerformance = avgAcadPerformance;
       this.passingCourses = passingCourses;
    }
   
    public Integer getStudentId() {
        return this.studentId;
    }
    
    public void setStudentId(Integer studentId) {
        this.studentId = studentId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getTelephone() {
        return this.telephone;
    }
    
    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public int getZachNom() {
        return this.zachNom;
    }
    
    public void setZachNom(int zachNom) {
        this.zachNom = zachNom;
    }
    public Float getAvgAcadPerformance() {
        return this.avgAcadPerformance;
    }
    
    public void setAvgAcadPerformance(Float avgAcadPerformance) {
        this.avgAcadPerformance = avgAcadPerformance;
    }
    public Set getPassingCourses() {
        return this.passingCourses;
    }
    
    public void setPassingCourses(Set passingCourses) {
        this.passingCourses = passingCourses;
    }




}


